# Generated by Django 5.0.6 on 2024-09-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonModel',
            new_name='Person',
        ),
    ]
